export const hotels = [
    // --- SHIMLA (5 Hotels) ---
    {
        id: 'shimla-1',
        name: 'The Oberoi Cecil',
        location: 'Shimla, India',
        rating: 4.9,
        reviews: 2100,
        price: 15000,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&w=800',
        amenities: ['Spa', 'Heated Pool', 'Fine Dining', 'Valley View'],
        type: 'Hotel',
        description: 'A heritage hotel offering colonial charm and stunning views of the Himalayas.',
        rooms: [{ id: 's1-r1', name: 'Luxury Room', price: 15000, capacity: 2, description: 'Classic decor with valley views' }]
    },
    {
        id: 'shimla-2',
        name: 'Wildflower Hall',
        location: 'Shimla, India',
        rating: 4.9,
        reviews: 1800,
        price: 22000,
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?ixlib=rb-4.0.3&w=800',
        amenities: ['Infinity Pool', 'Spa', 'Nature Walks', 'Tennis'],
        type: 'Resort',
        description: 'Luxury resort located 8,000 feet above sea level.',
        rooms: [{ id: 's2-r1', name: 'Premier Mountain View', price: 22000, capacity: 2, description: 'Unmatched mountain vistas' }]
    },
    {
        id: 'shimla-3',
        name: 'Hotel Combermere',
        location: 'Shimla, India',
        rating: 4.3,
        reviews: 3500,
        price: 6500,
        image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?ixlib=rb-4.0.3&w=800',
        amenities: ['Gym', 'Game Room', 'Bar', 'Mall Road Access'],
        type: 'Hotel',
        description: 'Located right next to the tourism lift on Mall Road.',
        rooms: [{ id: 's3-r1', name: 'Deluxe Room', price: 6500, capacity: 2, description: 'Modern amenities near Mall Road' }]
    },
    {
        id: 'shimla-4',
        name: 'Snow Valley Resorts',
        location: 'Shimla, India',
        rating: 4.4,
        reviews: 1200,
        price: 5500,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?ixlib=rb-4.0.3&w=800',
        amenities: ['AC', 'WiFi', 'Restaurant', 'Parking'],
        type: 'Resort',
        description: 'One of the biggest hotels in Shimla, offering panoramic views.',
        rooms: [{ id: 's4-r1', name: 'Premium Room', price: 5500, capacity: 3, description: 'Spacious room for families' }]
    },
    {
        id: 'shimla-5',
        name: 'Hotel Shingar Mall Road',
        location: 'Shimla, India',
        rating: 4.1,
        reviews: 1529,
        price: 3500,
        image: '/shimla-custom.png',
        amenities: ['WiFi', 'Restaurant', 'Couple Friendly'],
        type: 'Hotel',
        description: 'Located in the heart of Mall Road, offering convenient stays.',
        rooms: [{ id: 's5-r1', name: 'Standard Room', price: 3500, capacity: 2, description: 'Budget friendly on Mall Road' }]
    },

    // --- GOA (5 Hotels) ---
    {
        id: 'goa-1',
        name: 'Taj Exotica Resort & Spa',
        location: 'Goa, India',
        rating: 4.8,
        reviews: 3000,
        price: 25000,
        image: 'https://images.unsplash.com/photo-1571896349842-6e53ce41be03?ixlib=rb-4.0.3&w=800',
        amenities: ['Private Beach', 'Golf', 'Spa', 'Pool'],
        type: 'Resort',
        description: 'Mediterranean-style resort located on the Benaulim beach.',
        rooms: [{ id: 'g1-r1', name: 'Garden Villa', price: 25000, capacity: 2, description: 'Private pool villa' }]
    },
    {
        id: 'goa-2',
        name: 'W Goa',
        location: 'Goa, India',
        rating: 4.6,
        reviews: 1500,
        price: 18000,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&w=800',
        amenities: ['Nightclub', 'Beach Access', 'Rock Pool'],
        type: 'Hotel',
        description: 'Vibrant luxury hotel at Vagator Beach.',
        rooms: [{ id: 'g2-r1', name: 'Wonderful Room', price: 18000, capacity: 2, description: 'Stylish and modern' }]
    },
    {
        id: 'goa-3',
        name: 'Lemon Tree Amarante Beach Resort',
        location: 'Goa, India',
        rating: 4.2,
        reviews: 2500,
        price: 6000,
        image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-4.0.3&w=800',
        amenities: ['Pool', 'Spa', 'WiFi'],
        type: 'Resort',
        description: 'Portuguese style architecture near Candolim Beach.',
        rooms: [{ id: 'g3-r1', name: 'Heritage Room', price: 6000, capacity: 2, description: 'Classic decor' }]
    },
    {
        id: 'goa-4',
        name: 'Zostel Goa (Morjim)',
        location: 'Goa, India',
        rating: 4.5,
        reviews: 800,
        price: 1200,
        image: 'https://images.unsplash.com/photo-1555854743-e3c746dd0971?ixlib=rb-4.0.3&w=800',
        amenities: ['Dorm', 'WiFi', 'Common Area', 'Events'],
        type: 'Hostel',
        description: 'Vibrant backpacker hostel steps from the beach.',
        rooms: [{ id: 'g4-r1', name: 'Bunk Bed', price: 1200, capacity: 1, description: 'Bed in 4-bed dorm' }]
    },
    {
        id: 'goa-5',
        name: 'Goa Beachfront Resort',
        location: 'Goa, India',
        rating: 4.3,
        reviews: 1200,
        price: 4500,
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
        amenities: ['Pool', 'Bar', 'Beach Access'],
        type: 'Resort',
        description: 'Steps away from the vibrant Baga beach.',
        rooms: [{ id: 'g5-r1', name: 'Poolside Cottage', price: 4500, capacity: 2, description: 'Direct pool access' }]
    },

    // --- MANALI (5 Hotels) ---
    {
        id: 'manali-1',
        name: 'Span Resort and Spa',
        location: 'Manali, India',
        rating: 4.7,
        reviews: 1200,
        price: 14000,
        image: '/manali-custom.png',
        amenities: ['River View', 'Spa', 'Pool'],
        type: 'Resort',
        description: 'Luxury riverside resort on the banks of Beas.',
        rooms: [{ id: 'm1-r1', name: 'Premium Room', price: 14000, capacity: 2, description: 'Riverside views' }]
    },
    {
        id: 'manali-2',
        name: 'The Manali Inn',
        location: 'Manali, India',
        rating: 4.5,
        reviews: 1800,
        price: 5500,
        image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=800',
        amenities: ['Discotheque', 'Spa', 'Gym'],
        type: 'Hotel',
        description: 'Famous for its nightlife and river views.',
        rooms: [{ id: 'm2-r1', name: 'Classic Room', price: 5500, capacity: 2, description: 'Comfortable stay' }]
    },
    {
        id: 'manali-3',
        name: 'Sterling Manali',
        location: 'Manali, India',
        rating: 4.2,
        reviews: 900,
        price: 4800,
        image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?ixlib=rb-4.0.3&w=800',
        amenities: ['Bonfire', 'Activity Center', 'Restaurant'],
        type: 'Resort',
        description: 'Set amidst apple orchards with stunning views.',
        rooms: [{ id: 'm3-r1', name: 'Privilege Room', price: 4800, capacity: 3, description: 'Great for families' }]
    },
    {
        id: 'manali-4',
        name: 'Zostel Manali (Old Manali)',
        location: 'Manali, India',
        rating: 4.6,
        reviews: 1500,
        price: 1000,
        image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
        amenities: ['Garden', 'Cafe', 'WiFi'],
        type: 'Hostel',
        description: 'Generic backpacker vibe in the heart of Old Manali.',
        rooms: [{ id: 'm4-r1', name: 'Dorm Bed', price: 1000, capacity: 1, description: 'Social atmosphere' }]
    },
    {
        id: 'manali-5',
        name: 'Snow Valley Resorts',
        location: 'Manali, India',
        rating: 4.3,
        reviews: 2100,
        price: 3500,
        image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
        amenities: ['Lawns', 'Games', 'Buffet'],
        type: 'Resort',
        description: 'Surrounded by pine forests in the Log Huts area.',
        rooms: [{ id: 'm5-r1', name: 'Maharaja Room', price: 3500, capacity: 2, description: 'Royal decor' }]
    },

    // --- MUNNAR (5 Hotels) ---
    {
        id: 'munnar-1',
        name: 'Tea Valley Resort',
        location: 'Munnar, India',
        rating: 4.5,
        reviews: 1300,
        price: 4500,
        image: '/munnar-custom.png',
        amenities: ['Tea Garden Walk', 'Campfire', 'Restaurant'],
        type: 'Resort',
        description: 'Stay right in the middle of a tea plantation.',
        rooms: [{ id: 'mu1-r1', name: 'Tea Garden Cottage', price: 4500, capacity: 2, description: 'Greenery all around' }]
    },
    {
        id: 'munnar-2',
        name: 'Elixir Hills',
        location: 'Munnar, India',
        rating: 4.8,
        reviews: 600,
        price: 9000,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
        amenities: ['Infinity Pool', 'Spa', 'Trekking'],
        type: 'Resort',
        description: 'Luxury suites nestled in the dense rainforests.',
        rooms: [{ id: 'mu2-r1', name: 'Jacuzzi Suite', price: 9000, capacity: 2, description: 'Private jacuzzi with view' }]
    },
    {
        id: 'munnar-3',
        name: 'Blanket Hotel & Spa',
        location: 'Munnar, India',
        rating: 4.9,
        reviews: 2000,
        price: 12000,
        image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
        amenities: ['Waterfall View', 'Spa', 'Pool'],
        type: 'Hotel',
        description: 'Premium luxury hotel with views of the Attukad waterfalls.',
        rooms: [{ id: 'mu3-r1', name: 'Premium Room', price: 12000, capacity: 2, description: 'Sound of waterfalls' }]
    },
    {
        id: 'munnar-4',
        name: 'Zostel Munnar',
        location: 'Munnar, India',
        rating: 4.6,
        reviews: 500,
        price: 1100,
        image: 'https://images.unsplash.com/photo-1555854743-e3c746dd0971?w=800',
        amenities: ['Common Room', 'WiFi', 'Views'],
        type: 'Hostel',
        description: 'Budget stay with million dollar views.',
        rooms: [{ id: 'mu4-r1', name: 'Dorm Bed', price: 1100, capacity: 1, description: 'Best for solo travelers' }]
    },
    {
        id: 'munnar-5',
        name: 'Clouds Valley Hotel',
        location: 'Munnar, India',
        rating: 4.1,
        reviews: 900,
        price: 3000,
        image: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800',
        amenities: ['City Center', 'Restaurant', 'Banquet'],
        type: 'Hotel',
        description: 'Conveniently located in Munnar town.',
        rooms: [{ id: 'mu5-r1', name: 'Executive Room', price: 3000, capacity: 2, description: 'Access to town' }]
    },

    // --- GOKARNA (5 Hotels) ---
    {
        id: 'gokarna-1',
        name: 'Kudle Beach View Resort',
        location: 'Gokarna, India',
        rating: 4.2,
        reviews: 800,
        price: 3500,
        image: '/gokarna-new.png',
        amenities: ['Beach Access', 'Pool', 'Yoga'],
        type: 'Resort',
        description: 'Overlooking the famous Kudle Beach.',
        rooms: [{ id: 'gk1-r1', name: 'Sea View Cottage', price: 3500, capacity: 2, description: 'Sunset views' }]
    },
    {
        id: 'gokarna-2',
        name: 'Zostel Gokarna',
        location: 'Gokarna, India',
        rating: 4.7,
        reviews: 1500,
        price: 1300,
        image: 'https://images.unsplash.com/photo-1571896349842-6e53ce41be03?w=800',
        amenities: ['Ocean View', 'Cafe', 'Chill Area'],
        type: 'Hostel',
        description: 'Perched on a cliff with panoramic ocean views.',
        rooms: [{ id: 'gk2-r1', name: 'Dorm Bed', price: 1300, capacity: 1, description: 'Cliffside stay' }]
    },
    {
        id: 'gokarna-3',
        name: 'Sanskruti Quality Resort',
        location: 'Gokarna, India',
        rating: 4.0,
        reviews: 400,
        price: 4000,
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
        amenities: ['Pool', 'Restaurant', 'Cottages'],
        type: 'Resort',
        description: 'Peaceful resort slightly away from the beach crowds.',
        rooms: [{ id: 'gk3-r1', name: 'Premium Cottage', price: 4000, capacity: 2, description: 'Surrounded by nature' }]
    },
    {
        id: 'gokarna-4',
        name: 'Namaste Cafe',
        location: 'Gokarna, India',
        rating: 4.4,
        reviews: 2500,
        price: 2500,
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
        amenities: ['Beachfront', 'Restaurant', 'Shack'],
        type: 'Hotel',
        description: 'Ideally located on Om Beach.',
        rooms: [{ id: 'gk4-r1', name: 'Beach Room', price: 2500, capacity: 2, description: 'Step out onto the sand' }]
    },
    {
        id: 'gokarna-5',
        name: 'Kahani Paradise',
        location: 'Gokarna, India',
        rating: 4.9,
        reviews: 100,
        price: 20000,
        image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=800',
        amenities: ['Luxury', 'Infinity Pool', 'Private'],
        type: 'Villa',
        description: 'Exclusive luxury villa estate.',
        rooms: [{ id: 'gk5-r1', name: 'Royal Suite', price: 20000, capacity: 2, description: 'Ultimate luxury' }]
    },

    // --- LUXURY RESORTS (New Additions) ---
    { id: 'res-1', name: 'Soneva Jani', location: 'Maldives', rating: 5.0, reviews: 3000, price: 150000, image: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800', amenities: ['Water Slide', 'Private Lagoon'], type: 'Resort', description: 'Ultimate luxury with water slides into the lagoon.', rooms: [{ id: 'r1', name: 'Water Reserve', price: 150000, capacity: 4 }] },
    { id: 'res-2', name: 'Zuri Kumarakom', location: 'Kerala, India', rating: 4.7, reviews: 1200, price: 18000, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', amenities: ['Backwaters', 'Spa'], type: 'Resort', description: 'Luxury resort on the Kumarakom backwaters.', rooms: [{ id: 'r1', name: 'Lake View', price: 18000, capacity: 2 }] },
    { id: 'res-3', name: 'Oberoi Vanyavilas', location: 'Ranthambore, India', rating: 4.9, reviews: 800, price: 60000, image: 'https://images.unsplash.com/photo-1571896349842-6e53ce41be03?w=800', amenities: ['Safari', 'Luxury Tent'], type: 'Resort', description: 'India\'s leading luxury jungle resort.', rooms: [{ id: 'r1', name: 'Luxury Tent', price: 60000, capacity: 2 }] },

    // --- OTHERS (Generic placeholders for remaining locations to ensure functionality) ---
    { id: 'gen-1', name: 'Maldives Paradise', location: 'Maldives', rating: 4.8, reviews: 900, price: 45000, image: '/maldives-custom.jpg', amenities: ['Water Villa', 'Ocean'], type: 'Resort', description: 'Luxury stay.', rooms: [{ id: 'r1', name: 'Villa', price: 45000, capacity: 2 }] },
    { id: 'gen-2', name: 'Krabi Resort', location: 'Krabi, Thailand', rating: 4.5, reviews: 600, price: 8000, image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800', amenities: ['Beach', 'Pool'], type: 'Resort', description: 'Relaxing stay.', rooms: [{ id: 'r1', name: 'Room', price: 8000, capacity: 2 }] },
    { id: 'gen-3', name: 'Phuket Grand', location: 'Phuket, Thailand', rating: 4.6, reviews: 800, price: 9000, image: '/phuket-custom-new.png', amenities: ['Nightlife', 'Pool'], type: 'Hotel', description: 'Central.', rooms: [{ id: 'r1', name: 'Suite', price: 9000, capacity: 2 }] },
    { id: 'gen-4', name: 'Langkawi Sea', location: 'Langkawi, Malaysia', rating: 4.7, reviews: 400, price: 12000, image: '/langkawi-custom.png', amenities: ['Nature', 'Sea'], type: 'Resort', description: 'Nature stay.', rooms: [{ id: 'r1', name: 'Chalet', price: 12000, capacity: 2 }] },
    { id: 'gen-5', name: 'Ooty Heritage', location: 'Ooty, India', rating: 4.4, reviews: 500, price: 4000, image: '/ooty-custom.png', amenities: ['Garden', 'View'], type: 'Hotel', description: 'Colonial charm.', rooms: [{ id: 'r1', name: 'Room', price: 4000, capacity: 2 }] },
    { id: 'gen-6', name: 'Chandigarh Plaza', location: 'Chandigarh, India', rating: 4.3, reviews: 600, price: 5000, image: '/chandigarh-custom.png', amenities: ['City', 'WiFi'], type: 'Hotel', description: 'Business hotel.', rooms: [{ id: 'r1', name: 'Executive', price: 5000, capacity: 2 }] },
    { id: 'gen-7', name: 'Dehradun View', location: 'Dehradun, India', rating: 4.2, reviews: 300, price: 3500, image: '/dehradun-custom.png', amenities: ['Valley', 'Food'], type: 'Hotel', description: 'Valley views.', rooms: [{ id: 'r1', name: 'Std Room', price: 3500, capacity: 2 }] },
    { id: 'gen-8', name: 'Mysore Palace Stay', location: 'Mysore, India', rating: 4.5, reviews: 700, price: 4500, image: '/mysore-custom.png', amenities: ['Heritage', 'Clean'], type: 'Hotel', description: 'Near palace.', rooms: [{ id: 'r1', name: 'Royal', price: 4500, capacity: 2 }] },
    { id: 'gen-9', name: 'Pokhara Retreat', location: 'Pokhara, Nepal', rating: 4.6, reviews: 400, price: 3000, image: '/pokhara-custom.png', amenities: ['Lake', 'Mountains'], type: 'Hotel', description: 'Lake side.', rooms: [{ id: 'r1', name: 'View Room', price: 3000, capacity: 2 }] },
    { id: 'gen-10', name: 'Kasol Camps', location: 'Kasol, India', rating: 4.7, reviews: 200, price: 1500, image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800', amenities: ['Bonfire', 'Tent'], type: 'Hostel', description: 'Riverside camping.', rooms: [{ id: 'r1', name: 'Tent', price: 1500, capacity: 2 }] },
    { id: 'gen-11', name: 'Jodhpur Heritage', location: 'Jodhpur, India', rating: 4.6, reviews: 500, price: 6000, image: '/jodhpur-custom.png', amenities: ['Fort View', 'Tradition'], type: 'Heritage', description: 'Blue city stay.', rooms: [{ id: 'r1', name: 'Heritage', price: 6000, capacity: 2 }] },
    { id: 'gen-12', name: 'Udaipur Lake', location: 'Udaipur, India', rating: 4.8, reviews: 900, price: 10000, image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?w=800', amenities: ['Lake', 'Luxury'], type: 'Hotel', description: 'Romantic.', rooms: [{ id: 'r1', name: 'Lake View', price: 10000, capacity: 2 }] },
    { id: 'gen-13', name: 'Abu Dhabi Stay', location: 'Abu Dhabi, UAE', rating: 4.7, reviews: 400, price: 15000, image: '/abudhabi-custom.png', amenities: ['Luxury', 'Mall'], type: 'Hotel', description: 'City center.', rooms: [{ id: 'r1', name: 'Suite', price: 15000, capacity: 2 }] },
    { id: 'gen-14', name: 'Dubai Downtown', location: 'Dubai, UAE', rating: 4.8, reviews: 1200, price: 20000, image: '/dubai-custom.png', amenities: ['Burj View', 'Pool'], type: 'Hotel', description: 'Downtown luxury.', rooms: [{ id: 'r1', name: 'Sky Room', price: 20000, capacity: 2 }] },
    { id: 'gen-15', name: 'Tirupati Stay', location: 'Tirupati, India', rating: 4.3, reviews: 1500, price: 2500, image: '/tirupati-custom.png', amenities: ['Temple', 'Clean'], type: 'Hotel', description: 'Pilgrim stay.', rooms: [{ id: 'r1', name: 'Family', price: 2500, capacity: 4 }] },
    { id: 'gen-16', name: 'Varanasi Ghat', location: 'Varanasi, India', rating: 4.4, reviews: 800, price: 3000, image: 'https://images.unsplash.com/photo-1561359313-0639aad49ca6?w=800', amenities: ['Ghat', 'Spiritual'], type: 'Guesthouse', description: 'Ghat side.', rooms: [{ id: 'r1', name: 'Ghat View', price: 3000, capacity: 2 }] },
    { id: 'gen-17', name: 'Puri Beach', location: 'Puri, India', rating: 4.2, reviews: 900, price: 3500, image: '/puri-custom.png', amenities: ['Beach', 'Temple'], type: 'Hotel', description: 'Sea facing.', rooms: [{ id: 'r1', name: 'Sea View', price: 3500, capacity: 2 }] },
    { id: 'gen-18', name: 'Bhubaneswar City', location: 'Bhubaneswar, India', rating: 4.3, reviews: 400, price: 4000, image: '/bhubaneshwar-custom.png', amenities: ['City', 'Pool'], type: 'Hotel', description: 'Central.', rooms: [{ id: 'r1', name: 'Club', price: 4000, capacity: 2 }] },
    { id: 'gen-19', name: 'Amritsar Gold', location: 'Amritsar, India', rating: 4.6, reviews: 1000, price: 3000, image: '/amritsar-custom.png', amenities: ['Temple', 'Food'], type: 'Hotel', description: 'Near Golden Temple.', rooms: [{ id: 'r1', name: 'Pilgrim', price: 3000, capacity: 2 }] },
    { id: 'gen-20', name: 'Amsterdam City', location: 'Amsterdam, Netherlands', rating: 4.7, reviews: 800, price: 18000, image: '/amsterdam-custom.png', amenities: ['Canal', 'Bike'], type: 'Apartment', description: 'Canal house.', rooms: [{ id: 'r1', name: 'Suite', price: 18000, capacity: 2 }] },
    { id: 'gen-21', name: 'Hong Kong Central', location: 'Hong Kong', rating: 4.6, reviews: 900, price: 22000, image: '/hong-kong-custom.png', amenities: ['Skyline', 'Metro'], type: 'Hotel', description: 'Harbour view.', rooms: [{ id: 'r1', name: 'City', price: 22000, capacity: 2 }] },
    { id: 'gen-22', name: 'Mumbai Sea', location: 'Mumbai, India', rating: 4.5, reviews: 1500, price: 12000, image: 'https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=800', amenities: ['Sea', 'Luxury'], type: 'Hotel', description: 'Marine Drive.', rooms: [{ id: 'r1', name: 'Sea View', price: 12000, capacity: 2 }] },
    { id: 'gen-23', name: 'Pattaya Bay', location: 'Pattaya, Thailand', rating: 4.3, reviews: 600, price: 6000, image: '/pattaya-custom.png', amenities: ['Beach', 'Party'], type: 'Hotel', description: 'Walking street.', rooms: [{ id: 'r1', name: 'Ocean', price: 6000, capacity: 2 }] },
    // --- CITY HOTELS WITH AMENITIES (Enriching for Filters) ---
    { id: 'city-1', name: 'Urban Oasis Hotel', location: 'Bangalore, India', rating: 4.4, reviews: 1100, price: 4500, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', amenities: ['Pool', 'WiFi', 'Gym', 'Restaurant'], type: 'Hotel', description: 'Modern city hotel with all amenities.', rooms: [{ id: 'r1', name: 'City Room', price: 4500, capacity: 2 }] },
    { id: 'city-2', name: 'Grand Plaza', location: 'Hyderabad, India', rating: 4.3, reviews: 900, price: 5000, image: 'https://images.unsplash.com/photo-1517840901100-8179e982acb7?w=800', amenities: ['Pool', 'Spa', 'AC', 'Parking'], type: 'Hotel', description: 'Luxury in the city.', rooms: [{ id: 'r1', name: 'Club Room', price: 5000, capacity: 2 }] },
    { id: 'city-3', name: 'Seaside Apartments', location: 'Chennai, India', rating: 4.2, reviews: 500, price: 3000, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', amenities: ['WiFi', 'AC', 'Kitchen', 'Parking'], type: 'Apartment', description: 'Service apartments near the beach.', rooms: [{ id: 'r1', name: '1BHK', price: 3000, capacity: 2 }] },
    { id: 'city-4', name: 'Heritage Haveli', location: 'Jaipur, India', rating: 4.7, reviews: 1500, price: 8000, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800', amenities: ['Pool', 'Restaurant', 'Spa', 'WiFi'], type: 'Hotel', description: 'Traditional rajasthani hospitality.', rooms: [{ id: 'r1', name: 'Royal Suite', price: 8000, capacity: 2 }] },
    { id: 'city-5', name: 'Mountain Retreat', location: 'Mussoorie, India', rating: 4.5, reviews: 700, price: 6000, image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800', amenities: ['Heated Pool', 'Gym', 'WiFi', 'View'], type: 'Resort', description: 'Escape to the mountains.', rooms: [{ id: 'r1', name: 'Valley View', price: 6000, capacity: 2 }] },
];
